services:
  api-gateway:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_NAME: api-gateway
    ports:
      - '3000:3000'
    environment:
      - PORT=3000
      - USER_SERVICE_URL=user-service:5001
      - ORDER_SERVICE_URL=order-service:5002
    depends_on:
      - user-service
      - order-service
    networks:
      - grpc-network

  user-service:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_NAME: user-service
    ports:
      - '5001:5001'
    networks:
      - grpc-network

  order-service:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_NAME: order-service
    ports:
      - '5002:5002'
    networks:
      - grpc-network

networks:
  grpc-network:
    driver: bridge